name: Docker Login and Push
description: Logs into Docker registry and pushes an image

inputs:
  registry:
    description: Docker registry
    required: true
  username:
    description: Docker registry username
    required: true
  password:
    description: Docker registry password / token
    required: true
  image_name:
    description: Full image name
    required: true
  tag:
    description: Image tag
    required: true

runs:
  using: "composite"
  steps:
    - name: Run docker build
      shell: bash
      run: |
        echo "🔐 Logging in to ${{ inputs.registry }}"
        echo "${{ inputs.password }}" | docker login ${{ inputs.registry }} -u "${{ inputs.username }}" --password-stdin

        echo "🚀 Pushing ${{ inputs.image_name }}:${{ inputs.tag }}"
        docker push ${{ inputs.image_name }}:${{ inputs.tag }}