name: "GitOps Deploy"
description: "Updates deployment image in source-of-truth GitOps repository"
inputs:
  source_of_truth_repo:
    description: "The GitOps repository URL"
    required: true
  image_tag:
    description: "The Docker image tag to deploy"
    required: true
runs:
  using: "composite"
  steps:
    - name: Checkout Source of Truth Repo
      uses: actions/checkout@v4
      with:
        repository: ${{ inputs.source_of_truth_repo }}
        token: ${{ github.token }}

    - name: Update Deployment YAML
      shell: bash
      run: |
        cd ${{ github.event.repository.name }}
        sed -i "s/\(image:.*:\).*/\1${{ inputs.image_tag }}/" deployment.yml

    - name: Commit and Push Changes
      shell: bash
      run: |
        cd ${{ github.event.repository.name }}
        git add .
        git commit -m "Update image tag to ${{ inputs.image_tag }}"
        git push