name: "Pre-checks"
description: "Performs credential scan, commit sign-off check and license scanning"
inputs:
  license_scanning:
    required: true
    type: boolean
    default: true
  license_decision_file:
    required: true
    type: string
    default: 'doc/dependency_decisions.yml'

runs:
  using: "composite"
  steps:

    - name: check license scan
      if: ${{ inputs.license_scanning == 'true' }}
      shell: bash
      run: |
        echo "Installing license_finder"
        sudo apt update && sudo apt install -y ruby ruby-dev
        sudo gem install license_finder
        license_finder --project-path=. --decisions-file=${{ inputs.license_decision_file }}

        exit_code=$?
        if [[ $exit_code -ne 0 ]]; then
          echo "There are dependencies that need approval"
          exit 1
        else
          echo "All dependencies are approved"
        fi