name: DAST with OWASP ZAP


on: 
  workflow_call:
    inputs:
      download_artifacts:
        required: true
        type: boolean
      download_artifact_name:
        required: true
        type: string
      image_name:
        required: true
        type: string
      image_tag:
        required: true
        type: string
    secrets:
      GH_TOKEN:
        required: true
jobs:
  dast:
    runs-on: ubuntu-latest
    steps:
      - name: Download compile Source Code
        if: ${{ inputs.download_artifacts }}
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.download_artifact_name }}
          path: .

      - name: Download docker image artifact
        uses: actions/download-artifact@v4
        with:
          name: docker-image
          path: .

      - name: Load Docker image
        run: gunzip -c docker-image.tar.gz | docker load


      - name: Start application
        run: |
          echo "IMAGE_NAME=${{ inputs.image_name }}:${{ inputs.image_tag }}" > .env
          docker compose up -d


      - name: Run ZAP Full Scan
        uses: zaproxy/action-full-scan@v0.12.0
        with:
          token: ${{ secrets.GH_TOKEN }}
          target: 'http://localhost:8080'
          docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
          cmd_options: '-J report_json.json -z "-config urls.file=/zap/wrk/urls.txt"'
          fail_action: false


      - name: Validate ZAP Report for High Risk Issues
        run: |
          if grep -q 'High' report_json; then
            echo "High risk issues found in report!"
            exit 1
          else
            echo "No High risk issues found in report."
          fi