name: Run ECR Image Vulnerability Scan

on:
  workflow_call:
    inputs:
      ecr_repo:
        required: true
        type: string
      aws_region:
        required: true
        type: string
      download_artifacts:
        required: false
        type: boolean
        default: false
      download_artifact_name:
        required: false
        type: string
    secrets:
      AWS_IAM_ROLE_ATHENTICATION:
        required: true

jobs:
  ecr-image-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Download Source Code
        if: ${{ inputs.download_artifacts }}
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.download_artifact_name }}
          path: .

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_IAM_ROLE_ATHENTICATION }}
          role-session-name: GitHubActionSession
          aws-region: ${{ inputs.aws_region }}

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Set Image Tag
        id: vars
        run: |
          IMAGE_TAG=${{ github.ref_name }}-$(echo $GITHUB_SHA | head -c 8)
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV

      - name: Run Image Scan Script
        run: |
          chmod +x ./ecr-image-scan.sh && ./ecr-image-scan.sh ${{ inputs.ecr_repo }} ${{ env.IMAGE_TAG }} ${{ inputs.aws_region }}
