name: GitOps Deploy Trigger

on:
  workflow_call:
    inputs:
      gitops_repo:
        required: true
        type: string
    secrets:
      GH_TOKEN:
        required: true

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitOps Repository
        uses: actions/checkout@v4
        with:
          repository: ${{ inputs.gitops_repo }}
          token: ${{ secrets.GH_TOKEN }}

      - name: Determine Deployment Environment Path
        run: |
          BRANCH_NAME="${GITHUB_REF#refs/heads/}"
          APP_NAME="${{ github.event.repository.name }}"

          if [[ "$BRANCH_NAME" == release/* ]]; then
            echo "ENV_FOLDER=$APP_NAME/overlays/staging" >> $GITHUB_ENV
          elif [[ "$BRANCH_NAME" == main || "$BRANCH_NAME" == master ]]; then
            echo "ENV_FOLDER=$APP_NAME/overlays/prod" >> $GITHUB_ENV
          else
            echo "ENV_FOLDER=$APP_NAME/overlays/dev" >> $GITHUB_ENV
          fi

      - name: Update Image Tag in kustomization.yaml
        run: |
          IMAGE_TAG="${GITHUB_REF_NAME}-$(echo $GITHUB_SHA | head -c 8)"

          if [[ -f "$ENV_FOLDER/kustomization.yaml" ]]; then
            sed -i "s|\(newTag: \).*|\1$IMAGE_TAG|" "$ENV_FOLDER/kustomization.yaml"
            echo "Updated $ENV_FOLDER/kustomization.yaml with image tag: $IMAGE_TAG"
          else
            echo "ERROR: Cannot find $ENV_FOLDER/kustomization.yaml" >&2
            exit 1
          fi

      - name: Commit and Push Changes
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git add .
          git commit -m "Deploy: Update image tag to $IMAGE_TAG for ${{ github.event.repository.name }} on branch ${GITHUB_REF##*/}" || echo "No changes to commit."
          git push
