name: Maven Build Reusable

on:
  workflow_call:
    inputs:
      mvn_command:
        required: true
        type: string
      java_version:
        required: true
        type: string
      checkout:
        required: false
        type: boolean
        default: false
      upload_artifacts:
        required: false
        type: boolean
        default: false
      upload_artifact_name:
        required: false
        type: string
        default: 'compiled-source-code'
      download_artifacts:
        required: false
        type: boolean
        default: false
      download_artifact_name:
        required: false
        type: string
jobs:
  maven-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        if: ${{ inputs.checkout }}
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: ${{ inputs.java_version}}
          distribution: 'temurin'

      - name: Download Source Code
        if: ${{ inputs.download_artifacts }}
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.download_artifact_name }}
          path: .
     
      - name: Execute Maven
        run: mvn ${{ inputs.mvn_command }}

      - name: Upload compile Source Code
        if: ${{ inputs.upload_artifacts }}
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.upload_artifact_name }}
          path: .