# .github/workflows/reusable-maven.yml
name: Maven Build Reusable

on:
  workflow_call:
    inputs:
      mvn_command:
        required: true
        type: string
      java_version:
        required: true
        type: string
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: ${{ inputs.java_version }}
          distribution: 'temurin'

      - name: Execute Maven
        run: mvn ${{ inputs.mvn_command }}

