# .github/workflows/reusable-maven.yml
name: Maven Build Reusable

on:
  workflow_call:
    inputs:
      mvn_command:
        required: true
        type: string
      java_version:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: ${{ inputs.java_version }}
          distribution: 'temurin'

      - name: Execute Maven
        run: mvn ${{ inputs.mvn_command }}

      - name: Upload Source Code
        uses: actions/upload-artifact@v4
        with:
          name: source-code
          path: .