name: pre-checks

on:
 workflow_call:
   inputs:
      commit_sign_off:
        required: true
        type: string
      commit_message:
        required: false
        type: string
      upload_artifacts:
        required: false
        type: boolean
        default: false
      artifact_name:
        required: false
        type: string
        default: 'source-code'

jobs:
  prechecks:
   runs-on: ubuntu-latest
   steps:
    - name: checkout code
      uses: actions/checkout@v4
      with:
        path: .

    - name: credential-scan
      uses: gitleaks/gitleaks-action@v2

    - name: check-commit-sign-off
      uses: commit-check/commit-check-action@v1
      with:
        commit-signoff: ${{ inputs.commit_sign_off }}
        message: ${{ inputs.commit_message }}

    - name: Upload Source Code
      if: ${{ inputs.upload_artifacts }}
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.artifact_name }}
        path: .

    