name: pre-checks

on:
 workflow_call:
   inputs:
      commit_sign_off:
        required: true
        type: string
      commit_message:
        required: false
        type: string
      license_scanning:
        required: false
        type: boolean
        default: false
      license_decision_file:
        required: false
        type: string
        default: 'doc/dependency_decisions.yml'
      upload_artifacts:
        required: false
        type: boolean
        default: false
      artifact_name:
        required: false
        type: string
        default: 'source-code'


jobs:
  prechecks:
   runs-on: ubuntu-latest
   steps:
    - name: checkout code
      uses: actions/checkout@v4
      with:
        path: .

    - name: credential-scan
      uses: gitleaks/gitleaks-action@v2

    - name: check-commit-sign-off
      uses: commit-check/commit-check-action@v1
      with:
        commit-signoff: ${{ inputs.commit_sign_off }}
        message: ${{ inputs.commit_message }}



    - name: check license scan
      if: ${{ inputs.license_scanning }}
      run: |
        echo "Installing license_finder"
        sudo apt install ruby ruby-dev
        sudo gem install license_finder
        license_finder --project-path=. --decisions-file=${{ inputs.license_decision_file }}
        
        exit_code=$?

        if [[ $exit_code -ne 0 ]]; then
        echo "There are dependency's that need to approval"
        exit 1
        else
        echo "All dependencies are approved"
        fi

    - name: Upload Source Code
      if: ${{ inputs.upload_artifacts }}
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.artifact_name }}
        path: .

    