name: Send Slack Notification
on:
  workflow_call:
    inputs:
      channel_name:
        required: false
        type: string
      status:
        required: true
        type: string
      commit_author_name:
        required: true
        type: string
      commit_message:
        required: true
        type: string
      commit_id:
        required: true
        type: string
      run_id:
        required: true
        type: string
      image_url:
        required: false
        type: string
        default: "https://i0.wp.com/build5nines.com/wp-content/uploads/2024/05/GitHub_Actions_Featured_Image_2024.jpg"
      failed_stage:
        required: false
        type: string
    secrets:
      SLACK_WEBHOOK_URL:
        required: true

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Slack Notification
        uses: slackapi/slack-github-action@v2.0.0
        with:
          webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
          webhook-type: incoming-webhook
          payload: |
            {
              "channel": "${{ inputs.channel_name }}",
              "text": "${{ inputs.status == 'success' && '✅ Build Successful' || '❌ Build Failed' }}!\nCommit: `${{ inputs.commit_id }}`\nAuthor: *${{ inputs.commit_author_name }}*\nMessage: _${{ inputs.commit_message }}_",
                blocks: [
                  {
                    "type": "section",
                    "text": {
                      "type": "mrkdwn",
                      "text": "${{ inputs.status == 'success' && ':rocket: Deployment Triggered' || ':x: Build Failed in stage: ' + inputs.failed_stage }}\nCommit: `${{ inputs.commit_id }}`\nMessage: *${{ inputs.commit_message }}*"
                    },
                    "accessory": {
                      "type": "button",
                      "text": {
                        "type": "plain_text",
                        "text": "View Run",
                        "emoji": true
                      },
                      "url": "https://github.com/${{ github.repository }}/actions/runs/${{ inputs.run_id }}",
                      "action_id": "run"
                    }
                  },
                  {
                    "type": "image",
                    "image_url": "${{ inputs.image_url }}",
                    "alt_text": "GitHub Actions Notification"
                  }
                ]
            }