name: Send Slack Notification
on:
  workflow_call:
    inputs:
      commit_author_name:
        required: true
        type: string
      commit_message:
        required: true
        type: string
      commit_id:
        required: true
        type: string
      run_id:
        required: true
        type: string
    secrets:
      SLACK_WEBHOOK_URL:
        required: true

jobs:
  success:
    if: ${{ success() }}
    runs-on: ubuntu-latest
    steps:
      - name: Notify Slack on Success
        uses: slackapi/slack-github-action@v1.24.0
        with:
          payload: |
            {
              "blocks": [
                {
                  "type": "header",
                  "text": {
                    "type": "plain_text",
                    "text": "✅ Build Succeeded and Triggered for Deployment",
                    "emoji": true
                  }
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "*Author:* `${{ inputs.commit_author_name }}`\\n*Branch:* `${{ github.ref_name }}`\\n*Commit ID:* `${{ inputs.commit_id }}`\\n*Message:* ${{ toJson(inputs.commit_message) }}"
                  }
                },
                {
                  "type": "actions",
                  "elements": [
                    {
                      "type": "button",
                      "text": {
                        "type": "plain_text",
                        "text": "View Job",
                        "emoji": true
                      },
                      "url": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ inputs.run_id }}"
                    }
                  ]
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK

  failure:
    if: ${{ failure() }}
    runs-on: ubuntu-latest
    steps:
      - name: Notify Slack on Failure
        uses: slackapi/slack-github-action@v1.24.0
        with:
          payload: |
            {
              "blocks": [
                {
                  "type": "header",
                  "text": {
                    "type": "plain_text",
                    "text": "❌ Pipeline Failed",
                    "emoji": true
                  }
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "*Author:* `${{ inputs.commit_author_name }}`\\n*Branch:* `${{ github.ref_name }}`\\n*Commit ID:* `${{ inputs.commit_id }}`\\n*Message:* ${{ toJson(inputs.commit_message) }}"
                  }
                },
                {
                  "type": "actions",
                  "elements": [
                    {
                      "type": "button",
                      "text": {
                        "type": "plain_text",
                        "text": "View Job",
                        "emoji": true
                      },
                      "url": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ inputs.run_id }}"
                    }
                  ]
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK