on:
  workflow_call:
    inputs:
      channel_name:
        required: false
        type: string
      commit_author_name:
        required: true
        type: string
      commit_message:
        required: true
        type: string
      commit_id:
        required: true
        type: string
      run_id:
        required: true
        type: string
    secrets:
      SLACK_WEBHOOK_URL:
        required: true

jobs:
  notify:
    runs-on: ubuntu-latest
    needs:
      - test
    outputs:
      status: ${{ steps.set-status.outputs.status }}
      failed_stage: ${{ steps.set-status.outputs.failed_stage }}

    steps:
      - name: Determine Status and Failed Stage
        id: set-status
        run: |
          echo "Checking job results..."

          status="success"
          failed_stage=""

          for stage in test; do
            result="${{ needs[stage].result }}"
            if [ "$result" == "failure" ]; then
              status="failure"
              failed_stage="$stage"
              break
            fi
          done

          echo "status=$status" >> "$GITHUB_OUTPUT"
          echo "failed_stage=$failed_stage" >> "$GITHUB_OUTPUT"

      - name: Send Slack Notification
        uses: slackapi/slack-github-action@v2.0.0
        with:
          webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
          webhook-type: incoming-webhook
          payload: |
            {
              "channel": "${{ inputs.channel_name }}",
              "text": "${{ steps.set-status.outputs.status == 'success' && '✅ Build Successful!' || format('❌ Build Failed at stage: {0}', steps.set-status.outputs.failed_stage) }}",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "${{ steps.set-status.outputs.status == 'success' && format(':rocket: *Build Succeeded*\nBranch: `{0}`\nCommit: `{1}`\nMessage: _{2}_', github.ref_name, inputs.commit_id, inputs.commit_message) || format(':x: *Build Failed*\nStage: `{0}`\nBranch: `{1}`\nCommit: `{2}`\nMessage: _{3}_', steps.set-status.outputs.failed_stage, github.ref_name, inputs.commit_id, inputs.commit_message) }}"
                  },
                  "accessory": {
                    "type": "button",
                    "text": {
                      "type": "plain_text",
                      "text": "View Run",
                      "emoji": true
                    },
                    "url": "https://github.com/${{ github.repository }}/actions/runs/${{ inputs.run_id }}",
                    "action_id": "run"
                  }
                }
              ]
            }