name: test-2


on: 
  workflow_call:
    inputs:
      image_name:
        required: true
        type: string
      # image_tag:
      #   required: true
      #   type: string

jobs:
  test:
    runs-on: ubuntu-latest
    steps:    
    - name: print
      run: |
       echo "IMAGE_NAME=${{ inputs.image_name }}"